[package]
name = "sheldon-cross"
version = "0.0.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.54"
clap = { version = "3.1.1", features = ["derive"] }
upon = "0.6.0"

[[bin]]
name = "sheldon-cross"
path = "render.rs"
