[package]
name = "sheldon-cross"
version = "0.0.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.65"
argh = "0.1.9"
upon = "0.4.0"

[[bin]]
name = "sheldon-cross"
path = "render.rs"
