[package]
name = "sheldon-cross"
version = "0.0.0"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.38"
clap = "3.0.0-beta.2"
handlebars = "3.5.2"
serde_json = "1.0.62"

[[bin]]
name = "sheldon-cross"
path = "render.rs"
