FROM rustembedded/cross:aarch64-unknown-linux-musl

COPY install_openssl.sh /
RUN bash /install_openssl.sh linux-aarch64 aarch64-linux-musl-

ENV OPENSSL_DIR=/openssl \
    OPENSSL_STATIC=1 \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib

