FROM rustembedded/cross:x86_64-unknown-linux-gnu

COPY install_openssl.sh /
RUN bash /install_openssl.sh linux-x86_64

ENV OPENSSL_DIR=/openssl \
    LD_LIBRARY_PATH="/openssl/lib:${LD_LIBRARY_PATH}" \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib

