FROM ubuntu:16.04

COPY linux-image.sh /
RUN /linux-image.sh x86_64

FROM centos:7

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY qemu.sh /
RUN /qemu.sh x86_64 softmmu

COPY dropbear.sh /
RUN /dropbear.sh

COPY --from=0 /qemu /qemu

COPY linux-runner /

ENV CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner x86_64"


# OpenSSL
COPY install_openssl.sh /
RUN bash /install_openssl.sh linux-x86_64

ENV OPENSSL_DIR=/openssl \
    LD_LIBRARY_PATH="/openssl/lib:${LD_LIBRARY_PATH}" \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib
