FROM rustembedded/cross:aarch64-unknown-linux-gnu

COPY install_openssl.sh /
RUN bash /install_openssl.sh linux-aarch64 aarch64-linux-gnu-

ENV OPENSSL_DIR=/openssl \
    LD_LIBRARY_PATH="/openssl/lib:${LD_LIBRARY_PATH}" \
    OPENSSL_INCLUDE_DIR=/openssl/include \
    OPENSSL_LIB_DIR=/openssl/lib

