name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
        - { target: "x86_64-unknown-linux-gnu" }
        - { target: "x86_64-unknown-linux-musl" }
        - { target: "armv7-unknown-linux-gnueabihf" }
        - { target: "armv7-unknown-linux-musleabihf" }
        - { target: "aarch64-unknown-linux-gnu" }
        - { target: "aarch64-unknown-linux-musl" }

    name: build (${{ matrix.target}})
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        docker build \
          --tag "${{ github.sha }}" \
          --file "docker/Dockerfile.${{ matrix.target }}" \
          docker

    - name: Push
      if: startsWith(github.event.ref, 'refs/tags')
      run: |
        docker login --username rossmacarthur --password "${{ secrets.DOCKER_TOKEN }}"
        tag="rossmacarthur/sheldon-cross:${{ matrix.target }}-${GITHUB_REF#refs/tags/}"
        docker tag "${{ github.sha }}" "$tag"
        docker push "$tag"
